<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="romrobillos" failures="1" tests="12" name="testcase.LoginTest" time="49.829" errors="0" timestamp="2025-01-09T02:27:13 GMT+08:00" skipped="0">
  <testcase classname="testcase.LoginTest" name="testToLogin" time="3.080"/>
  <system-out/>
  <testcase classname="testcase.LoginTest" name="testToLogin" time="2.530"/>
  <system-out/>
  <testcase classname="testcase.LoginTest" name="testToLogin" time="3.186"/>
  <system-out/>
  <testcase classname="testcase.LoginTest" name="testToLogin" time="8.335"/>
  <system-out/>
  <testcase classname="testcase.LoginTest" name="testToLogin" time="3.293"/>
  <system-out/>
  <testcase classname="testcase.LoginTest" name="testInvalidLoginErrorMsg" time="3.724"/>
  <system-out/>
  <testcase classname="testcase.LoginTest" name="testLockedOutErrorMsg" time="3.557"/>
  <system-out/>
  <testcase classname="testcase.LoginTest" name="testResponseTime" time="4.571"/>
  <system-out/>
  <testcase classname="testcase.LoginTest" name="testResponseTime" time="2.883"/>
  <system-out/>
  <testcase classname="testcase.LoginTest" name="testResponseTime" time="7.951">
    <failure message="
Login took 6.0885376 seconds expecting &lt;=2.0 seconds expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
Login took 6.0885376 seconds expecting <=2.0 seconds expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at testcase.LoginTest.testResponseTime(LoginTest.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testResponseTime -->
  <system-out/>
  <testcase classname="testcase.LoginTest" name="testResponseTime" time="3.328"/>
  <system-out/>
  <testcase classname="testcase.LoginTest" name="testResponseTime" time="3.391"/>
  <system-out/>
</testsuite> <!-- testcase.LoginTest -->
